### ISSUE TITLE
Invalid location token {lwin}{pup} ?

### ISSUE THREAD

**Issue by max-sixty** [kijowski/kinesis#1]
This tool is superb! I'm very impressed.

I'm getting an invalid location token for `{lwin}{pup}`. Is that correct? It seems to work on the keyboard itself. Or is it a dvorak vs qwerty thing?

Thanks!

**Comment by kijowski** [comment]
Thanks for checking out my tool and raising the issue.

This is indeed a bug - I've already found where it is and will fix it in a moment
