### ISSUE TITLE
Dvorak mode

### ISSUE THREAD

**Issue by max-sixty** [kijowski/kinesis#4]
Hi @kijowski — I just used the tool again — it's really good for showing someone a layout. It deserves to be bundled with the keyboard...

One thing that it doesn't seem to take account of is when the remappings are different for a dvorak layout. e.g. 

```
[/]>[rctrl]
[\]>[hyphen]
```

...are different in a dvorak layout, and the Advantage 2 spec uses whatever layout has been set. I've indicated the correct version with arrows.

(I realize also the characters are different in dvorak, but that's less important)

![image](https://user-images.githubusercontent.com/5635139/143942002-1385a169-da1a-4c1a-8519-8d8975a9535c.png)

TBC, totally understand if this is non-trivial to implement, and thank you again for sharing the tool.

**Comment by stefano-ottolenghi** [comment]
Would be awesome if it were possible to select the keymap of the layer, so that previews on dvorak are possible.

**Comment by kijowski** [comment]
Hey, I just finished a fix for that, it's available at https://kinesis-git-add-dvorak-kijowski.vercel.app. I don't use Advantage much anymore - @stefano-ottolenghi can you check if your remap works as intended? And @max-sixty - sorry for the long wait :)

**Comment by stefano-ottolenghi** [comment]
It does look fine, thanks @kijowski !
